name: Create and publish a Docker image

# Triggers the workflow on push events to the 'release' branch and version tags 'v*'
on:
  push:
    branches:
      - release
    tags:
      - "v*"

# Global environment variables used across all jobs
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Permissions needed to read the repo and write packages to GitHub Packages
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Checks out the repository's code to the runner

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # Logs in to GitHub Container Registry to allow pushing images

      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest  # Always tag with 'latest'
            type=ref,event=tag     # Tag with the version number if pushed with a tag
        # Generates metadata for the image, such as tags and labels

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        # Builds the Docker image and pushes it to GitHub Packages